baseURL = "https://rote.dev/"
languageCode = "en-us"
title = "Rote Docs"
theme = "rote"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[markup]
  [markup.highlight]
    lineNos = true

[params]
primaryBackgroundColor = "#406db5"
primaryTextColor = "#fff"
showListPages = false
themeVariant = "dark"

[[menu.shortcuts]]
name = "GitHub Repository"
pre = "github"
url = "https://github.com/rote-docs/rote"
weight = 10

[[menu.shortcuts]]
name = "Docs Repository"
pre = "github"
url = "https://github.com/rote-docs/documentation"
weight = 20